#include "Constants.h"
#include <vector>
#include <string>
std::vector<std::pair<std::string, int>> CapooActionNameKeys = {
    {"idle_idle", 6},
    {"idle_full", 2},
    {"walk", 6},
    {"run", 9},
    {"wild", 5},
    {"roll", 5},
    {"air", 0},
    {"fall", 0},
    {"hit", 7},
    {"pet", 5},
    {"prone", 4},
    {"catchUp", 4},
    {"stackFog", 1},
    {"stackDown", 3},
    {"foodAppear", 4},
    {"chew", 0},
    {"enjoy", 3},
    {"pooing", 0},
    {"waitCleanPoo", 0},
    {"pooRemoving", 0},
    {"pooRemoveAfter", 0},
    {"dizzy", 4},
    {"summonAppear", 0},
    {"recycle", 0},
    {"merge", 0}
};
